version: "2"
services:
  adminer:
    image: asergey/adminer:latest
    container_name: koa_test.adminer
    environment:
      DB_HOST: mysql
      DB_USER: test_db
      DB_PASS: X3GuqTAL
    ports:
      - 3308:80
    links:
      - mysql
    logging:
      driver: none
  mysql:
    image: mysql:5.7.18
    container_name: koa_test.mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_db
      MYSQL_PASSWORD: X3GuqTAL
      MYSQL_ROOT_PASSWORD: eRV6Hspr
    logging:
      driver: none
  redis:
    image: redis:3
    container_name: koa_test.redis
    ports:
      - 6379:6379
    logging:
      driver: none
  redis-commander:
    image: tenstartups/redis-commander
    container_name: koa_test.redis-commander
    command: --redis-host redis
    ports:
      - 6380:8081
    links:
      - redis
    logging:
      driver: none
  nginx:
    image: nginx:mainline-alpine
    container_name: koa_test.snginx
    env_file:
      - .env
    volumes:
        - ./.extra/docker-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./.extra/docker-nginx/node.conf:/etc/nginx/node.conf:ro
        - ./static:/var/www/html
    extra_hosts:
        - "localbox:${MACHINE_IP}"
    ports:
      - 83:80